; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite][download][type] = ""
projects[campsite][download][url] = ""
projects[campsite][type] = "module"

projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_account][download][type] = ""
projects[campsite_account][download][url] = ""
projects[campsite_account][type] = "module"
projects[campsite_account][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_codesprint][download][type] = ""
projects[campsite_codesprint][download][url] = ""
projects[campsite_codesprint][type] = "module"
projects[campsite_codesprint][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_core][download][type] = ""
projects[campsite_core][download][url] = ""
projects[campsite_core][type] = "module"
projects[campsite_core][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_export_user_datas][download][type] = ""
projects[campsite_export_user_datas][download][url] = ""
projects[campsite_export_user_datas][type] = "module"
projects[campsite_export_user_datas][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_main_menu][download][type] = ""
projects[campsite_main_menu][download][url] = ""
projects[campsite_main_menu][type] = "module"
projects[campsite_main_menu][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_news][download][type] = ""
projects[campsite_news][download][url] = ""
projects[campsite_news][type] = "module"
projects[campsite_news][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_page][download][type] = ""
projects[campsite_page][download][url] = ""
projects[campsite_page][type] = "module"
projects[campsite_page][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_session][download][type] = ""
projects[campsite_session][download][url] = ""
projects[campsite_session][type] = "module"
projects[campsite_session][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_sponsor][download][type] = ""
projects[campsite_sponsor][download][url] = ""
projects[campsite_sponsor][type] = "module"
projects[campsite_sponsor][version] = "1.0"

projects[ckeditor][version] = "1.16"

projects[countries][version] = "2.3"

projects[date][version] = "2.8"

projects[ds][version] = "2.7"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.3"

projects[field_group][version] = "1.4"

projects[flag][version] = "3.5"

projects[panels][version] = "3.5"

projects[image_link_formatter][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[image_styles][download][type] = ""
projects[image_styles][download][url] = ""
projects[image_styles][type] = "module"
projects[image_styles][version] = "1.0"

projects[jquery_update][version] = "2.4"

projects[link][version] = "1.3"

projects[views][version] = "3.8"

projects[views_data_export][version] = "3.0-beta8"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[campsite_theme][download][type] = ""
projects[campsite_theme][download][url] = ""
projects[campsite_theme][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[iron15][download][type] = ""
projects[iron15][download][url] = ""
projects[iron15][type] = "theme"

